# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Rules(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 620)
        MainWindow.setMinimumSize(QtCore.QSize(621, 620))
        MainWindow.setMaximumSize(QtCore.QSize(621, 620))
        MainWindow.setStyleSheet("background-color: rgb(255, 221, 119);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 601, 551))
        self.textBrowser.setStyleSheet("border-color:  rgb(255, 221, 119);")
        self.textBrowser.setObjectName("textBrowser")
        self.P2_label = QtWidgets.QLabel(self.centralwidget)
        self.P2_label.setGeometry(QtCore.QRect(260, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P2_label.setFont(font)
        self.P2_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.P2_label.setStyleSheet("")
        self.P2_label.setScaledContents(False)
        self.P2_label.setObjectName("P2_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PERUKE"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#000000;\">•  </span><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">Player 1 starting a round.</span><span style=\" font-size:11pt; color:#000000;\"><br />•  To set up the game both players get 2 sets of discs </span><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">with values of 1 to 6.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">(The discs have two sides a plain side &amp; a target. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">A target showing on a disc means it is vulnerable to capture, the plain side means it is safe)</span><span style=\" font-size:11pt; color:#000000;\"><br />• Each player lays their 2 sets of discs out horizontally in front of them in the following way:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">- With a primary row laid out 1 to 6, (horizontally from left to right), with all the discs safe (plain side up).</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">- With a secondary row laid out above the primary row, 6 to 1 with all discs unsafe (target side up). </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">(i.e the 6 disc on the secondary row is directly above the 1 disc on the primary row, the 5 above the 2, etc.This set up prevents confusion later in the round as to what discs are primary or secondary.)</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">• On their 1st roll of the dice a player can only use the values to make the discs on their own secondary row safe (turn from target side to plain).</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">When each player has had their initial roll they can then use the values of each of the dice rolled on subsequent turns to either:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">- Turn an opponents disc from their primary or secondary row from safe to vulnerable</span><span style=\" font-size:11pt; color:#000000;\"><br />- Turn one of their own discs from their primary or secondary row from vulnerable to safe<br />- Take an opponents disc from their primary or secondary row if it is vulnerable</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">When a disc is taken it is removed from play &amp; kept by the player who took it as part of their score</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">•</span><span style=\" font-size:11pt; color:#000000;\"> </span><span style=\" font-size:11pt; font-weight:600; color:#000000; background-color:transparent;\">The round plays until one player loses all of the discs from their primary row. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-size:11pt; color:#000000; background-color:transparent;\">The player that ends a round by taking their opponent’s last disc from their primary row, adds all of their own discs left in play to their score. They also take all of the remaining discs that are left vulnerable by their opponent and add these to their score. Discs that are left safe remain with that player as part of their score. The values of the discs a player has collected are added together &amp; recorded. The player with the highest combined score wins.</span></p></body></html>"))
        self.P2_label.setText(_translate("MainWindow", "   Rules"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Rules()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
