# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'winner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Winner(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 297)
        MainWindow.setMinimumSize(QtCore.QSize(423, 297))
        MainWindow.setMaximumSize(QtCore.QSize(423, 297))
        MainWindow.setStyleSheet("background-color: rgb(255, 221, 119);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.win_label = QtWidgets.QLabel(self.centralwidget)
        self.win_label.setGeometry(QtCore.QRect(100, 50, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.win_label.setFont(font)
        self.win_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_label.setStyleSheet("background-color: rgb(255, 147, 23);")
        self.win_label.setScaledContents(False)
        self.win_label.setObjectName("win_label")
        self.p1_score = QtWidgets.QLabel(self.centralwidget)
        self.p1_score.setGeometry(QtCore.QRect(30, 150, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p1_score.setFont(font)
        self.p1_score.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_score.setStyleSheet("background-color: rgb(255, 147, 23);")
        self.p1_score.setScaledContents(False)
        self.p1_score.setObjectName("p1_score")
        self.p2_score = QtWidgets.QLabel(self.centralwidget)
        self.p2_score.setGeometry(QtCore.QRect(230, 150, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.p2_score.setFont(font)
        self.p2_score.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p2_score.setStyleSheet("background-color: rgb(255, 147, 23);")
        self.p2_score.setScaledContents(False)
        self.p2_score.setObjectName("p2_score")
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(170, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ok.setFont(font)
        self.btn_ok.setStyleSheet("background-color: rgb(255, 147, 23);")
        self.btn_ok.setObjectName("btn_ok")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PERUKE"))
        self.win_label.setText(_translate("MainWindow", "     Player 2 WON!!!"))
        self.p1_score.setText(_translate("MainWindow", " Your Score: "))
        self.p2_score.setText(_translate("MainWindow", " Opponent Score: "))
        self.btn_ok.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Winner()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
